### ISSUE TITLE
vault source

### ISSUE THREAD

**Issue by supernovae** [zeroturnaround/configo#27]
https://github.com/hashicorp/vault

**Comment by bsideup** [comment]
Hi @supernovae ,

Will be implemented soon :)

Meanwhile, you can try fresh new source called "shell", it allows you to execute your own command. It's not officially released (yet), but you can get fresh trusted build from here: https://circleci.com/gh/zeroturnaround/configo/94#artifacts

So, if you have Vault's CLI available, then you can do:

```
export CONFIGO_SOURCE_0='{"type": "shell", "format":"json", "command":"vault read -format=json secret/password"'
```

**Comment by bsideup** [comment]
@supernovae could you please try this build? https://circleci.com/gh/zeroturnaround/configo/95#artifacts

It has experimental Vault support :)
You can also build from sources:

https://github.com/zeroturnaround/configo/tree/27-vault

**Comment by supernovae** [comment]
I'll give it a whirl! Thanks!

**Comment by bsideup** [comment]
@supernovae ping :)

**Comment by bsideup** [comment]
@supernovae Vault source was merged. It will be included in the next release which will happen really soon (most probably today or tomorrow)

**Comment by bsideup** [comment]
@supernovae https://github.com/zeroturnaround/configo/releases/tag/v0.2.0
